"""Scaffold a new skill directory (ТЗ F-405/F-408): ``make skill name=coffee``.

The generated body raises NotImplementedError on purpose: the ТЗ forbids
placeholders that pretend to succeed.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SKILLS_DIRNAME = "skills"
_NAME = re.compile(r"^[a-z][a-z0-9_]{1,40}$")

_MANIFEST = """name: {name}
description: {description}
scope: home          # hub | home
role: user           # admin | trusted | user | guest
caps: []             # client capabilities this skill needs, e.g. [speaker]
version: 0.1.0
enabled: false
"""

_SKILL = '''"""{name} skill - generated by hub.skill_scaffold."""
from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from hub.skills_runtime import SkillResult


class Args(BaseModel):
    """Arguments the model may pass; extra keys are rejected."""

    model_config = ConfigDict(extra="forbid")

    text: str = ""


async def run(ctx, args: Args) -> SkillResult:
    """Do the real work here.

    Until the body performs a real action the skill must not claim success -
    raise NotImplementedError instead of returning a fake result.
    """
    raise NotImplementedError("{name} skill body is not implemented yet")
'''


def scaffold(root: Path, name: str) -> Path:
    """Create ``skills/<name>/`` under ``root``; return the created directory."""
    if not _NAME.match(name or ""):
        raise ValueError("Skill name must be lowercase letters, digits or underscores (2-41 chars).")
    directory = Path(root) / SKILLS_DIRNAME / name
    if directory.exists():
        raise FileExistsError(f"{directory} already exists; scaffolding never overwrites.")
    directory.mkdir(parents=True)
    (directory / "manifest.yaml").write_text(
        _MANIFEST.format(name=name, description=f"{name} skill"), encoding="utf-8")
    (directory / "skill.py").write_text(_SKILL.format(name=name), encoding="utf-8")
    return directory


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="hub.skill_scaffold", description="Scaffold a new Rowan skill.")
    parser.add_argument("--name", required=True, help="skill directory name, e.g. coffee")
    parser.add_argument("--root", default=str(REPO_ROOT), help="repository root (default: current repo)")
    args = parser.parse_args(argv)
    try:
        directory = scaffold(Path(args.root), args.name)
    except (ValueError, FileExistsError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    print(f"created {directory}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
